apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: wordpress
  namespace: app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress
      app.kubernetes.io/instance: blog
