provider: aws
policy: sync
domainFilters:
  - "${HOSTED_ZONE_NAME}"
txtOwnerId: "${PROJECT_ENV}"
interval: 30s
logLevel: info
serviceAccount:
  create: true
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: "${EXTERNAL_DNS_ROLE_ARN}"

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

extraArgs:
  - --aws-zone-type=public
  - --events
  - --txt-prefix=external-dns-
  - --policy=sync
